Introduce skeleton pods service and api 🎉
aurae-runtime/aurae pull request #193
Opened 2022-12-24 20:58 UTC by krisnova

Signed-off-by: Kris Nóva <kris@nivenly.com>

2022-12-28 16:37 UTC, future-highway requested changes
Blocking the merge because the macro is not generating the right deno code.

aka, I'm requesting changes from myself

2022-12-28 16:37 UTC, future-highway commented on api/v0/runtime.proto
> +  rpc Stop(StopContainerRequest) returns (StopContainerResponse) {}
I still prefer these to be more verbose in their naming. E.g., `AllocatePod`, `StartContainer`, `StopContainer`, `FreePod`.

Not a big deal though

2022-12-29 15:09 UTC, dmah42 commented on auraescript/src/runtime.rs
> +/* -------------------------------------------------------------------------- *\
is this a generated file now?  it seems weird to have to repeat the contents of the proto.

2022-12-29 15:09 UTC, dmah42 commented on auraescript/src/runtime.rs
> +/* -------------------------------------------------------------------------- *\
oh i guess we did that anyway.

2022-12-29 15:09 UTC, dmah42 submitted a review, later dismissed

2022-12-29 20:55 UTC, future-highway approved these changes
LGTM

2022-12-29 20:55 UTC, merged